<?php

namespace Database\Seeders;

use App\Models\Ingredient;
use Illuminate\Database\Seeder;

class IngredientSeeder extends Seeder
{
    public function run(): void
    {
        $ingredients = [
            ['name' => 'Aceite de oliva', 'kcal' => 884, 'protein' => 0, 'fats' => 100, 'carbs' => 0, 'unit' => 'g', 'category' => 'grasa'],
            ['name' => 'aceite girasol', 'kcal' => 826, 'protein' => 0, 'fats' => 92, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'aceite oliva extra gran seleccion', 'kcal' => 822, 'protein' => 0, 'fats' => 91, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Aceitunas', 'kcal' => 145, 'protein' => 1, 'fats' => 15, 'carbs' => 3.8, 'unit' => 'g', 'category' => 'grasa'],
            ['name' => 'aceitunas sin hueso aliñadas', 'kcal' => 134, 'protein' => 1.9, 'fats' => 13, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'acelgas', 'kcal' => 10, 'protein' => 0.7, 'fats' => 0, 'carbs' => 1.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'agua', 'kcal' => 0, 'protein' => 0, 'fats' => 0, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Aguacate', 'kcal' => 160, 'protein' => 2, 'fats' => 15, 'carbs' => 9, 'unit' => 'g', 'category' => 'grasa'],
            ['name' => 'Ajos', 'kcal' => 149, 'protein' => 6.4, 'fats' => 0.5, 'carbs' => 33, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'Almendras', 'kcal' => 579, 'protein' => 21, 'fats' => 50, 'carbs' => 22, 'unit' => 'g', 'category' => 'grasa'],
            ['name' => 'altramuces', 'kcal' => 105, 'protein' => 9.6, 'fats' => 2, 'carbs' => 10, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Alubias', 'kcal' => 127, 'protein' => 9, 'fats' => 0.5, 'carbs' => 23, 'unit' => 'g', 'category' => 'carbohidratos'],
            ['name' => 'alubias a la jardinera', 'kcal' => 85, 'protein' => 4.8, 'fats' => 1.9, 'carbs' => 10.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'anchoas', 'kcal' => 192, 'protein' => 25, 'fats' => 10.1, 'carbs' => 0.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Arroz blanco', 'kcal' => 359, 'protein' => 7, 'fats' => 0.7, 'carbs' => 79, 'unit' => 'g', 'category' => 'carbohidratos'],
            ['name' => 'arroz congelado microondas', 'kcal' => 126, 'protein' => 2.7, 'fats' => 0.3, 'carbs' => 28, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Arroz integral', 'kcal' => 370, 'protein' => 8, 'fats' => 2.9, 'carbs' => 77, 'unit' => 'g', 'category' => 'carbohidratos'],
            ['name' => 'arroz integral largo', 'kcal' => 350, 'protein' => 7.6, 'fats' => 2.8, 'carbs' => 72, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'arroz tres delicias', 'kcal' => 109, 'protein' => 4.6, 'fats' => 1.4, 'carbs' => 19, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Atún', 'kcal' => 132, 'protein' => 28, 'fats' => 1, 'carbs' => 0, 'unit' => 'g', 'category' => 'proteina'],
            ['name' => 'atun aceite girasol (escurrido)', 'kcal' => 245, 'protein' => 21, 'fats' => 18, 'carbs' => 0.9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'atun aceite oliva (escurrido)', 'kcal' => 245, 'protein' => 21, 'fats' => 18, 'carbs' => 0.9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'atun con tomate', 'kcal' => 196, 'protein' => 13, 'fats' => 15, 'carbs' => 2.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'atun natural', 'kcal' => 98, 'protein' => 21, 'fats' => 1.2, 'carbs' => 0.9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Avena', 'kcal' => 389, 'protein' => 17, 'fats' => 7, 'carbs' => 66, 'unit' => 'g', 'category' => 'carbohidratos'],
            ['name' => 'Bacalao', 'kcal' => 82, 'protein' => 18, 'fats' => 0.7, 'carbs' => 0, 'unit' => 'g', 'category' => 'proteina'],
            ['name' => 'banderillas dulces', 'kcal' => 48, 'protein' => 1, 'fats' => 3.4, 'carbs' => 2.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'batido chocolate 0%', 'kcal' => 45, 'protein' => 2.2, 'fats' => 1.3, 'carbs' => 5.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'batido chocolate leche', 'kcal' => 61, 'protein' => 3.1, 'fats' => 0.9, 'carbs' => 10, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'batido fresa', 'kcal' => 51, 'protein' => 1.9, 'fats' => 0.5, 'carbs' => 9.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'bebida avena', 'kcal' => 47, 'protein' => 1.6, 'fats' => 0.7, 'carbs' => 8.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'bebida avena 0% azucar', 'kcal' => 35, 'protein' => 0.7, 'fats' => 1.4, 'carbs' => 4.7, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'bebida avena chocolate 0% azucar', 'kcal' => 44, 'protein' => 1.2, 'fats' => 1.9, 'carbs' => 5.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Berenjena', 'kcal' => 25, 'protein' => 1, 'fats' => 0.2, 'carbs' => 6, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'biscotes', 'kcal' => 396, 'protein' => 11, 'fats' => 7, 'carbs' => 70, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'brocoli', 'kcal' => 29, 'protein' => 3, 'fats' => 0.4, 'carbs' => 1.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'caballa aceite oliva (escurrido)', 'kcal' => 218, 'protein' => 25, 'fats' => 13, 'carbs' => 0.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'cacahuete desgrasado polvo', 'kcal' => 416, 'protein' => 46.7, 'fats' => 13.2, 'carbs' => 21, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'cafe avena', 'kcal' => 51, 'protein' => 1.1, 'fats' => 2.2, 'carbs' => 6.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'cafe con leche capuccino', 'kcal' => 59, 'protein' => 3, 'fats' => 1.3, 'carbs' => 8.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'cafe con leche descafeinado', 'kcal' => 74, 'protein' => 3.5, 'fats' => 2.5, 'carbs' => 9.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'cafe con leche expresso', 'kcal' => 56, 'protein' => 3, 'fats' => 1.2, 'carbs' => 8.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'cafe con leche light', 'kcal' => 42, 'protein' => 3, 'fats' => 0.8, 'carbs' => 5.7, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Calabacín', 'kcal' => 17, 'protein' => 1.2, 'fats' => 0.3, 'carbs' => 3.1, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'calamar salsa americana', 'kcal' => 162, 'protein' => 12, 'fats' => 11, 'carbs' => 3.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'canelones', 'kcal' => 144, 'protein' => 7.3, 'fats' => 5.7, 'carbs' => 15, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne albondigas', 'kcal' => 167, 'protein' => 17.9, 'fats' => 9.6, 'carbs' => 1.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne alitas de pollo', 'kcal' => 182, 'protein' => 17.2, 'fats' => 11.3, 'carbs' => 2.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne bacon', 'kcal' => 293, 'protein' => 16.6, 'fats' => 25, 'carbs' => 0.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne brochetas', 'kcal' => 154, 'protein' => 15.3, 'fats' => 10.3, 'carbs' => 0.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne chorizo oreado', 'kcal' => 400, 'protein' => 14, 'fats' => 35, 'carbs' => 2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne chuletas cerdo', 'kcal' => 144, 'protein' => 21.35, 'fats' => 5.89, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne chuletas ternera', 'kcal' => 110, 'protein' => 20.2, 'fats' => 2.59, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne cochinillo', 'kcal' => 286, 'protein' => 17.33, 'fats' => 23.48, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne costillas cerdo', 'kcal' => 257, 'protein' => 14, 'fats' => 15, 'carbs' => 16, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne filetes lomo', 'kcal' => 136, 'protein' => 20.54, 'fats' => 5.41, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne filetes pavo', 'kcal' => 103, 'protein' => 24, 'fats' => 0.9, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne filetes pollo', 'kcal' => 108, 'protein' => 22, 'fats' => 1.8, 'carbs' => 0.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne filetes ternera', 'kcal' => 135, 'protein' => 23.35, 'fats' => 3.92, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne frankfurt', 'kcal' => 165, 'protein' => 13, 'fats' => 12, 'carbs' => 0.9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne hamburguesas', 'kcal' => 192, 'protein' => 17.1, 'fats' => 13, 'carbs' => 2.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne higado ternera', 'kcal' => 140, 'protein' => 19.93, 'fats' => 4.85, 'carbs' => 2.91, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne kebab', 'kcal' => 193, 'protein' => 20, 'fats' => 12, 'carbs' => 1.69, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne lagartito iberico', 'kcal' => 225, 'protein' => 22, 'fats' => 14.45, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne lagrimitas limon', 'kcal' => 236, 'protein' => 15.4, 'fats' => 11.6, 'carbs' => 17.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne lomo adobado', 'kcal' => 117, 'protein' => 20, 'fats' => 3.6, 'carbs' => 0.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne longaniza', 'kcal' => 212, 'protein' => 13, 'fats' => 18, 'carbs' => 2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Carne molida (vacuno)', 'kcal' => 250, 'protein' => 26, 'fats' => 15, 'carbs' => 0, 'unit' => 'g', 'category' => 'proteina'],
            ['name' => 'carne picada cerdo', 'kcal' => 206, 'protein' => 17, 'fats' => 16, 'carbs' => 2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne picada vacuno', 'kcal' => 204, 'protein' => 19, 'fats' => 14, 'carbs' => 0.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne pinchitos', 'kcal' => 91, 'protein' => 19.7, 'fats' => 1, 'carbs' => 0.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'carne pollo asado troceado', 'kcal' => 189, 'protein' => 19, 'fats' => 12, 'carbs' => 0.7, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Cebollas', 'kcal' => 40, 'protein' => 1.1, 'fats' => 0.1, 'carbs' => 9, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'Cerdo (lomo)', 'kcal' => 143, 'protein' => 26, 'fats' => 3.5, 'carbs' => 0, 'unit' => 'g', 'category' => 'proteina'],
            ['name' => 'cereales arroz choco', 'kcal' => 386, 'protein' => 6.3, 'fats' => 1.9, 'carbs' => 84, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'cereales chocapic', 'kcal' => 393, 'protein' => 8.4, 'fats' => 4.8, 'carbs' => 76.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'cereales corn flakes 0%', 'kcal' => 373, 'protein' => 6.7, 'fats' => 1.1, 'carbs' => 82, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'cerveza shandy', 'kcal' => 37, 'protein' => 0.1, 'fats' => 0, 'carbs' => 8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Champiñones', 'kcal' => 22, 'protein' => 3.1, 'fats' => 0.3, 'carbs' => 3.3, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'champiñones laminados', 'kcal' => 21, 'protein' => 2.8, 'fats' => 0.1, 'carbs' => 1.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Claras de huevo', 'kcal' => 52, 'protein' => 11, 'fats' => 0.2, 'carbs' => 0.7, 'unit' => 'g', 'category' => 'proteina'],
            ['name' => 'Coliflor', 'kcal' => 25, 'protein' => 1.9, 'fats' => 0.3, 'carbs' => 5, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'copos de avena', 'kcal' => 375, 'protein' => 14, 'fats' => 1.3, 'carbs' => 59, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'corazones de alcachofa', 'kcal' => 26, 'protein' => 1.7, 'fats' => 0.4, 'carbs' => 3.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'croquetas', 'kcal' => 205, 'protein' => 7.4, 'fats' => 10, 'carbs' => 20, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce berlinas', 'kcal' => 488, 'protein' => 6.9, 'fats' => 34, 'carbs' => 38, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce bocaditos cacao', 'kcal' => 460, 'protein' => 5.3, 'fats' => 28, 'carbs' => 47, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce bollicao', 'kcal' => 223, 'protein' => 4.8, 'fats' => 8.4, 'carbs' => 31.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce bollo chocolate', 'kcal' => 353, 'protein' => 8.6, 'fats' => 16, 'carbs' => 42, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce conguitos', 'kcal' => 554, 'protein' => 14.5, 'fats' => 35.4, 'carbs' => 42, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce cortadillo cabello angel', 'kcal' => 426, 'protein' => 4, 'fats' => 15, 'carbs' => 68, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce croissant cacao', 'kcal' => 500, 'protein' => 6.2, 'fats' => 31, 'carbs' => 47, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce croissant chocolate', 'kcal' => 531, 'protein' => 4.5, 'fats' => 34.3, 'carbs' => 51.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce donetes', 'kcal' => 504, 'protein' => 5, 'fats' => 32, 'carbs' => 48, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce donuts', 'kcal' => 410, 'protein' => 5.4, 'fats' => 24, 'carbs' => 42, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce donuts chocolate', 'kcal' => 470, 'protein' => 6.4, 'fats' => 31, 'carbs' => 40, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce dulce roditas chocolate blanco (philipinos)', 'kcal' => 502, 'protein' => 6.6, 'fats' => 24, 'carbs' => 64, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce galletas limon', 'kcal' => 499, 'protein' => 5, 'fats' => 23, 'carbs' => 67, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce galletas oreo', 'kcal' => 104, 'protein' => 1.2, 'fats' => 4.3, 'carbs' => 15, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce galletas tosta rica', 'kcal' => 463, 'protein' => 7.5, 'fats' => 15, 'carbs' => 73, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce huesitos', 'kcal' => 500, 'protein' => 6.5, 'fats' => 23, 'carbs' => 66, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce kinder bueno', 'kcal' => 573, 'protein' => 7.9, 'fats' => 37, 'carbs' => 50, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce kit kat', 'kcal' => 512, 'protein' => 6.7, 'fats' => 26, 'carbs' => 60, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce magdalenas', 'kcal' => 415, 'protein' => 5, 'fats' => 21, 'carbs' => 51, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce magdalenas chocolate', 'kcal' => 457, 'protein' => 5.4, 'fats' => 24, 'carbs' => 54, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce tortas aceite', 'kcal' => 493, 'protein' => 6, 'fats' => 24, 'carbs' => 61, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'dulce tortitas arroz yogur', 'kcal' => 467, 'protein' => 7.2, 'fats' => 20, 'carbs' => 63, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido cabecero lomo', 'kcal' => 270, 'protein' => 31, 'fats' => 16, 'carbs' => 0.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido chorizo', 'kcal' => 341, 'protein' => 24, 'fats' => 26, 'carbs' => 2.7, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido chorizo iberico', 'kcal' => 494, 'protein' => 24, 'fats' => 43.6, 'carbs' => 1.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido jamon', 'kcal' => 234, 'protein' => 30, 'fats' => 12, 'carbs' => 1.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido jamon cocido braseado', 'kcal' => 99, 'protein' => 18, 'fats' => 2.3, 'carbs' => 1.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido jamon pavo', 'kcal' => 87, 'protein' => 14.2, 'fats' => 2.5, 'carbs' => 1.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido jamon reducido sal', 'kcal' => 99, 'protein' => 15, 'fats' => 3, 'carbs' => 3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido lacon horno', 'kcal' => 212, 'protein' => 12, 'fats' => 16, 'carbs' => 5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido lomo embuchado', 'kcal' => 201, 'protein' => 34, 'fats' => 6.5, 'carbs' => 1.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido mortadela', 'kcal' => 254, 'protein' => 10, 'fats' => 22, 'carbs' => 4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido mortadela aceitunas', 'kcal' => 244, 'protein' => 10.5, 'fats' => 20, 'carbs' => 5.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido mortadela siciliana', 'kcal' => 244, 'protein' => 13.2, 'fats' => 6.5, 'carbs' => 7.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido paleta cocida', 'kcal' => 109, 'protein' => 19, 'fats' => 3, 'carbs' => 1.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido pechuga pavo braseada', 'kcal' => 99, 'protein' => 18, 'fats' => 2.3, 'carbs' => 1.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido pechuga pavo cocida', 'kcal' => 81, 'protein' => 16, 'fats' => 0.5, 'carbs' => 3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido pechuga pollo', 'kcal' => 84, 'protein' => 16.9, 'fats' => 1.2, 'carbs' => 1.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido pollo relleno', 'kcal' => 170, 'protein' => 18.46, 'fats' => 6.87, 'carbs' => 7.29, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido salchichon', 'kcal' => 372, 'protein' => 22, 'fats' => 30, 'carbs' => 3.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'embutido salchichon iberico', 'kcal' => 493, 'protein' => 25.6, 'fats' => 42.6, 'carbs' => 1.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'empanada de atun', 'kcal' => 226, 'protein' => 7.9, 'fats' => 10, 'carbs' => 26, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'empanada pollo setas', 'kcal' => 272, 'protein' => 7.2, 'fats' => 12, 'carbs' => 33, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'empanadillas atun', 'kcal' => 255, 'protein' => 5.6, 'fats' => 13.5, 'carbs' => 28, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'espinaca', 'kcal' => 27, 'protein' => 2.9, 'fats' => 0.4, 'carbs' => 1.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Espinacas', 'kcal' => 23, 'protein' => 2.9, 'fats' => 0.4, 'carbs' => 3.6, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'fabada', 'kcal' => 140, 'protein' => 7.3, 'fats' => 7.4, 'carbs' => 9.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fideos orientales', 'kcal' => 98, 'protein' => 2.1, 'fats' => 4, 'carbs' => 13, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fideos pollo', 'kcal' => 324, 'protein' => 14.9, 'fats' => 2.4, 'carbs' => 59.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Fresas', 'kcal' => 32, 'protein' => 0.7, 'fats' => 0.3, 'carbs' => 7.7, 'unit' => 'g', 'category' => 'fruta'],
            ['name' => 'fruta aguacate', 'kcal' => 159, 'protein' => 2, 'fats' => 14, 'carbs' => 3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta albaricoque', 'kcal' => 48, 'protein' => 1.4, 'fats' => 0.39, 'carbs' => 11.12, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta banana', 'kcal' => 89, 'protein' => 1.09, 'fats' => 0.33, 'carbs' => 22.84, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta caqui', 'kcal' => 70, 'protein' => 0.58, 'fats' => 0.19, 'carbs' => 18.59, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta cebolla', 'kcal' => 42, 'protein' => 0.92, 'fats' => 0.08, 'carbs' => 10.11, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta cebolla fresca', 'kcal' => 32, 'protein' => 1.83, 'fats' => 0.19, 'carbs' => 7.34, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta chirimolla', 'kcal' => 74, 'protein' => 1.65, 'fats' => 0.62, 'carbs' => 17.7, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta ciruela roja', 'kcal' => 46, 'protein' => 0.7, 'fats' => 0.28, 'carbs' => 11.42, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta fresas', 'kcal' => 32, 'protein' => 0.67, 'fats' => 0.3, 'carbs' => 7.68, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta kiwi', 'kcal' => 61, 'protein' => 1.14, 'fats' => 0.52, 'carbs' => 14.66, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta limones', 'kcal' => 25, 'protein' => 0.38, 'fats' => 0, 'carbs' => 8.63, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta macedonia', 'kcal' => 69, 'protein' => 0.4, 'fats' => 0.1, 'carbs' => 16.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta mandarina', 'kcal' => 43, 'protein' => 0.8, 'fats' => 0, 'carbs' => 9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta manzana fuji', 'kcal' => 52, 'protein' => 0.26, 'fats' => 0.17, 'carbs' => 13.81, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta manzana golden', 'kcal' => 52, 'protein' => 0.26, 'fats' => 0.17, 'carbs' => 13.81, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta melocoton', 'kcal' => 39, 'protein' => 0.91, 'fats' => 0.25, 'carbs' => 9.54, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta melon', 'kcal' => 36, 'protein' => 0.54, 'fats' => 0.14, 'carbs' => 9.08, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta naranja', 'kcal' => 47, 'protein' => 0.94, 'fats' => 0.12, 'carbs' => 11.75, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta nectarina', 'kcal' => 44, 'protein' => 1.06, 'fats' => 0.32, 'carbs' => 10.55, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta paraguayo', 'kcal' => 49, 'protein' => 0.83, 'fats' => 0.19, 'carbs' => 12.23, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta pera', 'kcal' => 64, 'protein' => 1, 'fats' => 0, 'carbs' => 16, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta persimon', 'kcal' => 69, 'protein' => 0.66, 'fats' => 0, 'carbs' => 14.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta pina', 'kcal' => 56, 'protein' => 0.5, 'fats' => 0.5, 'carbs' => 13, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta platano', 'kcal' => 90, 'protein' => 1.1, 'fats' => 0.33, 'carbs' => 23.27, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta sandia', 'kcal' => 30, 'protein' => 0.61, 'fats' => 0.15, 'carbs' => 7.55, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fruta uva negra', 'kcal' => 67, 'protein' => 0.68, 'fats' => 0.15, 'carbs' => 17.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'frutos secos almendras', 'kcal' => 603, 'protein' => 25, 'fats' => 51, 'carbs' => 5.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'frutos secos almendras tostadas', 'kcal' => 626, 'protein' => 22, 'fats' => 55, 'carbs' => 4.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'frutos secos anacardos fritos', 'kcal' => 617, 'protein' => 22.4, 'fats' => 50, 'carbs' => 16, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'frutos secos anacardos naturales', 'kcal' => 604, 'protein' => 21.9, 'fats' => 48.2, 'carbs' => 19, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'frutos secos avellanas', 'kcal' => 671, 'protein' => 16, 'fats' => 64, 'carbs' => 3.9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'frutos secos cacahuetes miel', 'kcal' => 591, 'protein' => 21, 'fats' => 44, 'carbs' => 25, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'frutos secos cacahuetes salados', 'kcal' => 596, 'protein' => 29.5, 'fats' => 48.5, 'carbs' => 7.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'frutos secos datiles', 'kcal' => 298, 'protein' => 2, 'fats' => 0.5, 'carbs' => 68.9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'frutos secos nueces', 'kcal' => 716, 'protein' => 17, 'fats' => 70, 'carbs' => 2.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'frutos secos pasas', 'kcal' => 324, 'protein' => 3.1, 'fats' => 1.1, 'carbs' => 73, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'frutos secos pipas calabaza', 'kcal' => 583, 'protein' => 35.3, 'fats' => 47.9, 'carbs' => 3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'frutos secos pipas girasol', 'kcal' => 665, 'protein' => 22, 'fats' => 61, 'carbs' => 3.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'frutos secos pistachos', 'kcal' => 617, 'protein' => 24.8, 'fats' => 51.1, 'carbs' => 10, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'fuet', 'kcal' => 421, 'protein' => 27.5, 'fats' => 34, 'carbs' => 1.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Garbanzos', 'kcal' => 164, 'protein' => 9, 'fats' => 2.6, 'carbs' => 27, 'unit' => 'g', 'category' => 'carbohidratos'],
            ['name' => 'garbanzos riojana', 'kcal' => 129, 'protein' => 5.8, 'fats' => 6.4, 'carbs' => 10.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'gazpacho', 'kcal' => 40, 'protein' => 0.9, 'fats' => 2.6, 'carbs' => 3.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'guacamole', 'kcal' => 149, 'protein' => 1.9, 'fats' => 13.7, 'carbs' => 2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Guisantes', 'kcal' => 81, 'protein' => 5.4, 'fats' => 0.4, 'carbs' => 14, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'helado almendrado', 'kcal' => 324, 'protein' => 4.7, 'fats' => 19.8, 'carbs' => 31.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'helado kinder', 'kcal' => 283, 'protein' => 3.6, 'fats' => 16, 'carbs' => 31, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'helado nocciola', 'kcal' => 403, 'protein' => 4.1, 'fats' => 27.1, 'carbs' => 35.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'helado vainilla chocolate nata', 'kcal' => 197, 'protein' => 3.3, 'fats' => 10, 'carbs' => 23, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'huevos', 'kcal' => 150, 'protein' => 12.5, 'fats' => 11.1, 'carbs' => 0.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Huevos (1 unidad = 50g)', 'kcal' => 155, 'protein' => 13, 'fats' => 11, 'carbs' => 1.1, 'unit' => 'g', 'category' => 'proteina'],
            ['name' => 'hummus', 'kcal' => 311, 'protein' => 6, 'fats' => 25.8, 'carbs' => 11.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Jamón serrano', 'kcal' => 265, 'protein' => 25, 'fats' => 18, 'carbs' => 0, 'unit' => 'g', 'category' => 'proteina'],
            ['name' => 'jamon taquitos', 'kcal' => 234, 'protein' => 33.7, 'fats' => 10.6, 'carbs' => 1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'judia verde', 'kcal' => 31, 'protein' => 1.9, 'fats' => 0.2, 'carbs' => 4.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Judías negras', 'kcal' => 132, 'protein' => 9, 'fats' => 0.5, 'carbs' => 24, 'unit' => 'g', 'category' => 'carbohidratos'],
            ['name' => 'Judías verdes', 'kcal' => 31, 'protein' => 1.8, 'fats' => 0.1, 'carbs' => 7, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'langostinos rebozados', 'kcal' => 185, 'protein' => 8.1, 'fats' => 4.5, 'carbs' => 27.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'lasaña boloñesa', 'kcal' => 143, 'protein' => 7.4, 'fats' => 6.1, 'carbs' => 14, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'lasaña espinacas', 'kcal' => 165, 'protein' => 5.9, 'fats' => 10, 'carbs' => 12, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'leche condensada', 'kcal' => 322, 'protein' => 7.4, 'fats' => 8, 'carbs' => 55, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'leche condensada desnatada', 'kcal' => 274, 'protein' => 8.5, 'fats' => 0.5, 'carbs' => 59, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'leche en polvo desnatada', 'kcal' => 357, 'protein' => 32.5, 'fats' => 1, 'carbs' => 54.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'leche entera', 'kcal' => 63, 'protein' => 3.1, 'fats' => 3.6, 'carbs' => 4.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'leche fresca', 'kcal' => 62, 'protein' => 3.1, 'fats' => 3.5, 'carbs' => 4.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'leche semidesnatada', 'kcal' => 46, 'protein' => 3.1, 'fats' => 1.6, 'carbs' => 4.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'leche soja', 'kcal' => 44, 'protein' => 3.4, 'fats' => 2, 'carbs' => 2.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Lechuga', 'kcal' => 15, 'protein' => 1.4, 'fats' => 0.2, 'carbs' => 2.9, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'lentejas', 'kcal' => 132, 'protein' => 5.1, 'fats' => 8.4, 'carbs' => 8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'limon exprimido', 'kcal' => 29, 'protein' => 0, 'fats' => 0, 'carbs' => 7.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'macarrones', 'kcal' => 366, 'protein' => 12, 'fats' => 1.5, 'carbs' => 74, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'maiz dulce', 'kcal' => 75, 'protein' => 2.6, 'fats' => 2.3, 'carbs' => 9.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'mantequilla', 'kcal' => 734, 'protein' => 0.5, 'fats' => 81, 'carbs' => 0.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'mantequilla cacahuete', 'kcal' => 618, 'protein' => 30, 'fats' => 50, 'carbs' => 7, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Manzana', 'kcal' => 52, 'protein' => 0.3, 'fats' => 0.2, 'carbs' => 14, 'unit' => 'g', 'category' => 'fruta'],
            ['name' => 'mejillones escabeche', 'kcal' => 170, 'protein' => 17, 'fats' => 9, 'carbs' => 1.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Merluza', 'kcal' => 87, 'protein' => 19, 'fats' => 0.7, 'carbs' => 0, 'unit' => 'g', 'category' => 'proteina'],
            ['name' => 'merluza empanada', 'kcal' => 189, 'protein' => 11, 'fats' => 10.1, 'carbs' => 13.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'mermelada fresa', 'kcal' => 194, 'protein' => 0.5, 'fats' => 0, 'carbs' => 47, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'migas de coliflor', 'kcal' => 20, 'protein' => 1.3, 'fats' => 0, 'carbs' => 2.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'mix de pepinillos y cebollitas', 'kcal' => 19, 'protein' => 1.2, 'fats' => 0.5, 'carbs' => 2.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Naranja', 'kcal' => 47, 'protein' => 0.9, 'fats' => 0.1, 'carbs' => 12, 'unit' => 'g', 'category' => 'fruta'],
            ['name' => 'nata para cocinar', 'kcal' => 163, 'protein' => 2, 'fats' => 15, 'carbs' => 5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'nocilla', 'kcal' => 230, 'protein' => 6.3, 'fats' => 30.9, 'carbs' => 57.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Nueces', 'kcal' => 654, 'protein' => 15, 'fats' => 65, 'carbs' => 14, 'unit' => 'g', 'category' => 'grasa'],
            ['name' => 'nuggets pollo', 'kcal' => 230, 'protein' => 10.4, 'fats' => 13.4, 'carbs' => 16.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'palitos surimi', 'kcal' => 90, 'protein' => 7.9, 'fats' => 0.8, 'carbs' => 12.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pan', 'kcal' => 278, 'protein' => 9.2, 'fats' => 1.6, 'carbs' => 56, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Pan blanco', 'kcal' => 265, 'protein' => 9, 'fats' => 3.2, 'carbs' => 49, 'unit' => 'g', 'category' => 'carbohidratos'],
            ['name' => 'pan hamburguesa', 'kcal' => 277, 'protein' => 9.4, 'fats' => 6.2, 'carbs' => 44, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Pan integral', 'kcal' => 247, 'protein' => 13, 'fats' => 3.4, 'carbs' => 41, 'unit' => 'g', 'category' => 'carbohidratos'],
            ['name' => 'pan molde sin corteza', 'kcal' => 237, 'protein' => 8.2, 'fats' => 3.1, 'carbs' => 42, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Parmesano', 'kcal' => 431, 'protein' => 38, 'fats' => 29, 'carbs' => 4.1, 'unit' => 'g', 'category' => 'lacteo'],
            ['name' => 'Pasta (macarrones)', 'kcal' => 371, 'protein' => 13, 'fats' => 1.5, 'carbs' => 75, 'unit' => 'g', 'category' => 'carbohidratos'],
            ['name' => 'patatas', 'kcal' => 68, 'protein' => 1.9, 'fats' => 0, 'carbs' => 14.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'patatas fritas congeladas', 'kcal' => 143, 'protein' => 2.3, 'fats' => 4.6, 'carbs' => 21, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pate higado', 'kcal' => 356, 'protein' => 15.1, 'fats' => 28.6, 'carbs' => 1.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Pavo (pechuga)', 'kcal' => 135, 'protein' => 30, 'fats' => 1, 'carbs' => 0, 'unit' => 'g', 'category' => 'proteina'],
            ['name' => 'Pepino', 'kcal' => 16, 'protein' => 0.7, 'fats' => 0.1, 'carbs' => 3.6, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'pescado atun fresco', 'kcal' => 103, 'protein' => 24.2, 'fats' => 0.4, 'carbs' => 0.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pescado bacalao', 'kcal' => 51, 'protein' => 14, 'fats' => 3, 'carbs' => 2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pescado chipirones', 'kcal' => 95, 'protein' => 15.06, 'fats' => 1.92, 'carbs' => 3.18, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pescado dorada', 'kcal' => 173, 'protein' => 37.74, 'fats' => 1.43, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pescado gamba pelada', 'kcal' => 72, 'protein' => 14.7, 'fats' => 1, 'carbs' => 1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pescado merluza', 'kcal' => 90, 'protein' => 20, 'fats' => 1.7, 'carbs' => 0.15, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pescado pez espada', 'kcal' => 121, 'protein' => 19.8, 'fats' => 0.01, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pescado poton', 'kcal' => 81, 'protein' => 17, 'fats' => 0.9, 'carbs' => 1.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pescado salmon', 'kcal' => 146, 'protein' => 21.62, 'fats' => 5.93, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pescado salmon salvaje', 'kcal' => 224, 'protein' => 20, 'fats' => 16, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pescado sardinas', 'kcal' => 178, 'protein' => 22, 'fats' => 9.8, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'philadelpia light', 'kcal' => 130, 'protein' => 9, 'fats' => 8.3, 'carbs' => 4.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'picos', 'kcal' => 416, 'protein' => 11.2, 'fats' => 6.2, 'carbs' => 77.7, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'picos salados', 'kcal' => 466, 'protein' => 9.7, 'fats' => 18.3, 'carbs' => 63.9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Pimientos', 'kcal' => 31, 'protein' => 1, 'fats' => 0.3, 'carbs' => 6, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'pimientos asados', 'kcal' => 31, 'protein' => 0.5, 'fats' => 0.2, 'carbs' => 6.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pimientos piquillo', 'kcal' => 40, 'protein' => 1, 'fats' => 0.4, 'carbs' => 7.7, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pimientos rojos', 'kcal' => 26, 'protein' => 0.99, 'fats' => 0.3, 'carbs' => 6.03, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pimientos verdes', 'kcal' => 20, 'protein' => 0.86, 'fats' => 0.17, 'carbs' => 4.65, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Piñones', 'kcal' => 673, 'protein' => 13, 'fats' => 68, 'carbs' => 13, 'unit' => 'g', 'category' => 'grasa'],
            ['name' => 'Pistachos', 'kcal' => 560, 'protein' => 20, 'fats' => 45, 'carbs' => 28, 'unit' => 'g', 'category' => 'grasa'],
            ['name' => 'pizza atun bacon', 'kcal' => 262, 'protein' => 12.7, 'fats' => 12.3, 'carbs' => 25.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pizza jamon queso', 'kcal' => 224, 'protein' => 14, 'fats' => 7.5, 'carbs' => 25.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'pizza prosciutto', 'kcal' => 207, 'protein' => 9.6, 'fats' => 6.5, 'carbs' => 26, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Plátano', 'kcal' => 89, 'protein' => 1.1, 'fats' => 0.3, 'carbs' => 23, 'unit' => 'g', 'category' => 'fruta'],
            ['name' => 'Pollo (pechuga)', 'kcal' => 109, 'protein' => 23, 'fats' => 1.2, 'carbs' => 0, 'unit' => 'g', 'category' => 'proteina'],
            ['name' => 'proteinas (whey protein)', 'kcal' => 380, 'protein' => 73, 'fats' => 5.9, 'carbs' => 8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'queso brie', 'kcal' => 347, 'protein' => 17, 'fats' => 31, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'queso burgos', 'kcal' => 164, 'protein' => 10.9, 'fats' => 11.5, 'carbs' => 4.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'queso cabra', 'kcal' => 335, 'protein' => 17, 'fats' => 29.2, 'carbs' => 1.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Queso cheddar', 'kcal' => 403, 'protein' => 25, 'fats' => 33, 'carbs' => 1.3, 'unit' => 'g', 'category' => 'lacteo'],
            ['name' => 'queso cottage', 'kcal' => 99, 'protein' => 14, 'fats' => 4, 'carbs' => 1.7, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'queso curado', 'kcal' => 431, 'protein' => 25, 'fats' => 36, 'carbs' => 1.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'queso fresco', 'kcal' => 168, 'protein' => 11.8, 'fats' => 11.4, 'carbs' => 4.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'queso fresco batido', 'kcal' => 46, 'protein' => 8, 'fats' => 0.1, 'carbs' => 3.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'queso lonchas fundido', 'kcal' => 242, 'protein' => 11.8, 'fats' => 16, 'carbs' => 12, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'queso lonchas tierno', 'kcal' => 378, 'protein' => 21, 'fats' => 32, 'carbs' => 1.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Queso mozzarella', 'kcal' => 280, 'protein' => 28, 'fats' => 17, 'carbs' => 3.1, 'unit' => 'g', 'category' => 'lacteo'],
            ['name' => 'queso porciones', 'kcal' => 151, 'protein' => 11.5, 'fats' => 9, 'carbs' => 6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'queso semicurado', 'kcal' => 421, 'protein' => 25, 'fats' => 35, 'carbs' => 1.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Quinoa', 'kcal' => 368, 'protein' => 14, 'fats' => 6, 'carbs' => 64, 'unit' => 'g', 'category' => 'carbohidratos'],
            ['name' => 'rabas empanadas', 'kcal' => 175, 'protein' => 9.7, 'fats' => 9.6, 'carbs' => 12.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'refresco coca cola', 'kcal' => 42, 'protein' => 0, 'fats' => 0, 'carbs' => 10.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'refresco te limon zero', 'kcal' => 3, 'protein' => 0, 'fats' => 0, 'carbs' => 0.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'refresco tinto limon zero', 'kcal' => 1, 'protein' => 0, 'fats' => 0, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'regañadas', 'kcal' => 448, 'protein' => 11.8, 'fats' => 15, 'carbs' => 65, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'requeson', 'kcal' => 160, 'protein' => 8.7, 'fats' => 11.6, 'carbs' => 5.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Ricotta', 'kcal' => 174, 'protein' => 11, 'fats' => 13, 'carbs' => 3, 'unit' => 'g', 'category' => 'lacteo'],
            ['name' => 'salchichas cocidas de pollo', 'kcal' => 187, 'protein' => 11.3, 'fats' => 13.4, 'carbs' => 4.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Salmón', 'kcal' => 208, 'protein' => 20, 'fats' => 13, 'carbs' => 0, 'unit' => 'g', 'category' => 'proteina'],
            ['name' => 'salmorejo', 'kcal' => 85, 'protein' => 1.1, 'fats' => 6.4, 'carbs' => 5.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'salsa agridulce', 'kcal' => 118, 'protein' => 0.5, 'fats' => 0.5, 'carbs' => 29, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'salsa boloñesa', 'kcal' => 122, 'protein' => 5.3, 'fats' => 6.7, 'carbs' => 9.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'salsa cocktail', 'kcal' => 425, 'protein' => 1, 'fats' => 43, 'carbs' => 10.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'salsa fritada pisto', 'kcal' => 92, 'protein' => 1.2, 'fats' => 4.8, 'carbs' => 10, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'salsa ketchup', 'kcal' => 115, 'protein' => 1.3, 'fats' => 0, 'carbs' => 27, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'salsa mahonesa', 'kcal' => 618, 'protein' => 0.9, 'fats' => 67, 'carbs' => 3.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'salsa mexicana', 'kcal' => 38, 'protein' => 1.4, 'fats' => 0.1, 'carbs' => 6.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'salsa mostaza', 'kcal' => 75, 'protein' => 3.8, 'fats' => 5.3, 'carbs' => 2.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'salsa ranchera', 'kcal' => 402, 'protein' => 1.1, 'fats' => 41.5, 'carbs' => 5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'salsa tomate frito', 'kcal' => 77, 'protein' => 1.5, 'fats' => 3.5, 'carbs' => 9.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'salteado patatas salchicha', 'kcal' => 149, 'protein' => 4.3, 'fats' => 6.6, 'carbs' => 17, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'san jacobos', 'kcal' => 179, 'protein' => 7.5, 'fats' => 3.5, 'carbs' => 29, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'sandwich atun', 'kcal' => 253, 'protein' => 12, 'fats' => 13, 'carbs' => 22, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'sandwich mixto', 'kcal' => 248, 'protein' => 14.2, 'fats' => 8.2, 'carbs' => 29.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Sardinas', 'kcal' => 208, 'protein' => 25, 'fats' => 11, 'carbs' => 0, 'unit' => 'g', 'category' => 'proteina'],
            ['name' => 'snack chetos pandilla', 'kcal' => 479, 'protein' => 5.8, 'fats' => 22.3, 'carbs' => 62.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'snack doritos', 'kcal' => 497, 'protein' => 6.6, 'fats' => 25.8, 'carbs' => 56.9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'snack fritos matutano', 'kcal' => 153, 'protein' => 1.9, 'fats' => 8.8, 'carbs' => 15.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'snack gusanitos (garfitos)', 'kcal' => 466, 'protein' => 6, 'fats' => 22, 'carbs' => 60, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'snack lays', 'kcal' => 153, 'protein' => 1.9, 'fats' => 8.8, 'carbs' => 15.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'snack papa delta', 'kcal' => 488, 'protein' => 3.9, 'fats' => 24, 'carbs' => 61, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'snack patatas fritas onduladas', 'kcal' => 550, 'protein' => 5.7, 'fats' => 34, 'carbs' => 53, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'snack patatas fritas onduladas jamon', 'kcal' => 540, 'protein' => 6, 'fats' => 32.4, 'carbs' => 53.9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'snack pringles', 'kcal' => 493, 'protein' => 3.9, 'fats' => 24.9, 'carbs' => 61.7, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'surimi', 'kcal' => 156, 'protein' => 7.9, 'fats' => 3.3, 'carbs' => 23.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'tallarines formaggio', 'kcal' => 393, 'protein' => 14.5, 'fats' => 7.9, 'carbs' => 65, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'tarta queso', 'kcal' => 295, 'protein' => 4.7, 'fats' => 20.9, 'carbs' => 22, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Tofu', 'kcal' => 76, 'protein' => 8, 'fats' => 4.8, 'carbs' => 1.9, 'unit' => 'g', 'category' => 'proteina'],
            ['name' => 'Tomate frito', 'kcal' => 91, 'protein' => 1.9, 'fats' => 5, 'carbs' => 9.4, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'Tomates', 'kcal' => 18, 'protein' => 0.9, 'fats' => 0.2, 'carbs' => 3.9, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'tortellini carne', 'kcal' => 267, 'protein' => 11, 'fats' => 7, 'carbs' => 38, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'tortillas trigo (fajitas)', 'kcal' => 294, 'protein' => 8.4, 'fats' => 5.8, 'carbs' => 50, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'tortitas arroz', 'kcal' => 363, 'protein' => 8.5, 'fats' => 2.8, 'carbs' => 75, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'tortitas arroz jamon serrano', 'kcal' => 467, 'protein' => 11, 'fats' => 10, 'carbs' => 79, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'tostadas de arroz y maiz sin gluten', 'kcal' => 387, 'protein' => 6.7, 'fats' => 2.3, 'carbs' => 84, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Uvas', 'kcal' => 69, 'protein' => 0.7, 'fats' => 0.2, 'carbs' => 18, 'unit' => 'g', 'category' => 'fruta'],
            ['name' => 'varitas merluza', 'kcal' => 195, 'protein' => 10, 'fats' => 9.5, 'carbs' => 17.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura calabacín', 'kcal' => 16, 'protein' => 1.21, 'fats' => 0.18, 'carbs' => 3.35, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura calabaza', 'kcal' => 26, 'protein' => 1, 'fats' => 0.1, 'carbs' => 6.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura cebolla', 'kcal' => 42, 'protein' => 0.92, 'fats' => 0.08, 'carbs' => 10.11, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura cebolla fresca', 'kcal' => 32, 'protein' => 1.83, 'fats' => 0.19, 'carbs' => 7.34, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura coles bruselas', 'kcal' => 42, 'protein' => 3.2, 'fats' => 0.3, 'carbs' => 4.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura congelada (coliflor, brocoli y zanahoria)', 'kcal' => 32, 'protein' => 2.6, 'fats' => 0.3, 'carbs' => 3.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura edamame', 'kcal' => 145, 'protein' => 12, 'fats' => 7.6, 'carbs' => 3.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura endivia', 'kcal' => 9, 'protein' => 1.1, 'fats' => 0.2, 'carbs' => 2.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura lechuga', 'kcal' => 16, 'protein' => 0.7, 'fats' => 0.6, 'carbs' => 1.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura lechuga 4 estaciones', 'kcal' => 17, 'protein' => 0.9, 'fats' => 0.5, 'carbs' => 2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura pepino', 'kcal' => 14, 'protein' => 0.62, 'fats' => 0.14, 'carbs' => 2.9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura rabanos', 'kcal' => 16, 'protein' => 0.68, 'fats' => 0.1, 'carbs' => 3.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura remolacha', 'kcal' => 43, 'protein' => 1.61, 'fats' => 0.17, 'carbs' => 9.56, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura tomate', 'kcal' => 18, 'protein' => 0.88, 'fats' => 0.2, 'carbs' => 3.92, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'verdura zanahoria', 'kcal' => 41, 'protein' => 0.93, 'fats' => 0.24, 'carbs' => 9.58, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'vinagre', 'kcal' => 20, 'protein' => 0, 'fats' => 0, 'carbs' => 0, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'vinagre balsamico', 'kcal' => 123, 'protein' => 0.98, 'fats' => 0, 'carbs' => 25.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur arroz con leche', 'kcal' => 139, 'protein' => 3.2, 'fats' => 3.7, 'carbs' => 23.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur batido fresa 0%', 'kcal' => 33, 'protein' => 3.3, 'fats' => 0.3, 'carbs' => 4.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur batido frutos silvestres 0%', 'kcal' => 33, 'protein' => 3.3, 'fats' => 0.3, 'carbs' => 4.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur bifidus frutos silvestres 0%', 'kcal' => 46, 'protein' => 3.8, 'fats' => 0.1, 'carbs' => 7.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur coco 0%', 'kcal' => 35, 'protein' => 4.3, 'fats' => 0.1, 'carbs' => 4.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur frutas', 'kcal' => 91, 'protein' => 3.6, 'fats' => 2.7, 'carbs' => 13.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur gelatina', 'kcal' => 1, 'protein' => 0, 'fats' => 0, 'carbs' => 0.2, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur griego fresa', 'kcal' => 139, 'protein' => 3.3, 'fats' => 7.8, 'carbs' => 13.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur griego ligero natural', 'kcal' => 60, 'protein' => 5.8, 'fats' => 2, 'carbs' => 4.7, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur natillas', 'kcal' => 127, 'protein' => 3.8, 'fats' => 4.4, 'carbs' => 18.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur natillas galleta', 'kcal' => 152, 'protein' => 3.8, 'fats' => 4, 'carbs' => 24.9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur natural', 'kcal' => 62, 'protein' => 3.7, 'fats' => 3.4, 'carbs' => 4.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur natural 0% azucares', 'kcal' => 36, 'protein' => 4.3, 'fats' => 0.1, 'carbs' => 4.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur panna cotta', 'kcal' => 201, 'protein' => 3.3, 'fats' => 11, 'carbs' => 21, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur petit', 'kcal' => 101, 'protein' => 7.5, 'fats' => 3, 'carbs' => 11, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur piña coco 0%', 'kcal' => 34, 'protein' => 3.3, 'fats' => 0.4, 'carbs' => 4.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur proteinas arandanos', 'kcal' => 53, 'protein' => 8.3, 'fats' => 0.1, 'carbs' => 5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur proteinas fresa', 'kcal' => 53, 'protein' => 8.3, 'fats' => 0.1, 'carbs' => 5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur proteinas limon', 'kcal' => 53, 'protein' => 8.3, 'fats' => 0.1, 'carbs' => 5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur proteinas mango y maracuya', 'kcal' => 56, 'protein' => 8.3, 'fats' => 0.1, 'carbs' => 5.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'yogur proteinas natural', 'kcal' => 52, 'protein' => 10, 'fats' => 0.5, 'carbs' => 3.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'Zanahorias', 'kcal' => 41, 'protein' => 0.9, 'fats' => 0.2, 'carbs' => 10, 'unit' => 'g', 'category' => 'verdura'],
            ['name' => 'zumo fruta + leche mediterraneo', 'kcal' => 15, 'protein' => 0.4, 'fats' => 0, 'carbs' => 3.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'zumo fruta leche tropical', 'kcal' => 21, 'protein' => 0.3, 'fats' => 0, 'carbs' => 4.8, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'zumo melocoton', 'kcal' => 27, 'protein' => 0.5, 'fats' => 0.1, 'carbs' => 5.6, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'zumo melocotón uva', 'kcal' => 55, 'protein' => 0.7, 'fats' => 0.2, 'carbs' => 12.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'zumo mosto tinto', 'kcal' => 62, 'protein' => 0.2, 'fats' => 0, 'carbs' => 15.3, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'zumo multivitaminas sin azucares', 'kcal' => 22, 'protein' => 0.4, 'fats' => 0.1, 'carbs' => 4.5, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'zumo naranja', 'kcal' => 44, 'protein' => 0.7, 'fats' => 0.1, 'carbs' => 9.9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'zumo naranja clementina.', 'kcal' => 42, 'protein' => 0.6, 'fats' => 0.1, 'carbs' => 9.7, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'zumo naranja, mango y zanahoria', 'kcal' => 23, 'protein' => 0.3, 'fats' => 0, 'carbs' => 5.4, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'zumo pera', 'kcal' => 27, 'protein' => 0.2, 'fats' => 0.1, 'carbs' => 6.1, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'zumo piña/uva', 'kcal' => 54, 'protein' => 0.6, 'fats' => 0, 'carbs' => 12.9, 'unit' => 'g', 'category' => 'otros'],
            ['name' => 'zumo sunny florida', 'kcal' => 13, 'protein' => 0, 'fats' => 0, 'carbs' => 2.6, 'unit' => 'g', 'category' => 'otros'],
        ];

        foreach ($ingredients as $ingredient) {
            Ingredient::firstOrCreate(
                ['name' => $ingredient['name']],
                $ingredient
            );
        }
    }
}
